### ISSUE TITLE
Structure of the course

### ISSUE THREAD

**Issue by s-weigand** [students-teach-students/python-tools-for-students#3]
How should we structure the course?
I think it is important that the course has a structure that builds up, on elements taught already.

Here is my first draft:

1. How to use Jupyter Lab (see #2)
2. Quick recap on Python basics
3. Analytical calculations in Python (sympy basics)
4. Numerical calculations in Python (numpy basics/first matplotlib plots)
5. Visualisation of data (matplotlib basics)
6. Handeling and cleaning data (pandas basics)
7. Fitting data (scipy basics)
8. Numerical solving of equations (odeint, general nummerical integration...)
9. Report automataisation with Python and LaTeX
10. Cool interactiv stuff (Jupyter widgets, Plotly, ....)

**Comment by ghost** [comment]
Concernig 7. What about ddeint, sdeint, networks and stuff?

**Comment by ghost** [comment]
And there is also a big issue with the analysis of data (finding maximums, pulse widths, root mean squares) which would be practical to automatize.

**Comment by s-weigand** [comment]
@noiseflow thanks for your feedback.
Atm this is just a first draft, on what we plan to do and in which order it will be most consistent.

DDE's you can solve utilizing [odeint](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html) and providing an extra array for 'looking back'.

I didn't work with SDE's and networks (which kind do you mean btw.) as of yet, so it would be cool if you could provide some examples in new issues. For the sake of teaching this should be easy to grasp examples and not some full blown quantum systems.

For the analysis of data this planned to be done in **6. Fitting data (scipy basics)**.
A general automatization of fitting won't be possible, since fitting depends on the used model and initial parameter guess. But we can provide code-snippets to easily look up, like a function that does the fit with the user provided data, model and initial parameter guess, an plots the original data together with the fit result and displays the found best parameters.

**Comment by redbluee** [comment]
> How should we structure the course?
> I think it is important that the course has a structure that builds up, on elements taught already.
> 
> Here is my first draft:
> 
> 1. How to use Jupyter Lab (see #2)
> 2. Quick recap on Python basics
> 3. Analytical calculations in Python (sympy basics)
> 4. Numerical calculations in Python (numpy basics/first matplotlib plots)
> 5. Visualisation of data (matplotlib basics)
> 6. Handeling and cleaning data (pandas basics)
> 7. Fitting data (scipy basics)
> 8. Numerical solving of equations (odeint, general nummerical integration...)
> 9. Report automataisation with Python and LaTeX
> 10. Cool interactiv stuff (Jupyter widgets, Plotly, ....)

Let's stick to that
