### ISSUE TITLE
How much of git do we want to teach?

### ISSUE THREAD

**Issue by s-weigand** [students-teach-students/python-tools-for-students#34]
**Is your feature request related to a problem? Please describe.**
Most students that have no/only little experience in programming don't know `git` or how to use it. 
Do we want to teach git and if yes how much of it do we want to teach?

**Describe the solution you'd like**
IMO `git` in more detail (`commit`, `branches`, `cherrypick`), would be a huge benefit for students.
Also we could tell the about GUI tools like [GitKraken](https://www.gitkraken.com/). 
But knowing how to use `git` with the CLI should be mendatory, since `GitKraken` sometimes has "hickups", which you can only fix with the CLI.

**Describe alternatives you've considered**
Just teach the basics of `git`, so people are able to contribute to the project itself (`CONTRIBUTING.md` #9)

**Comment by s-weigand** [comment]
Also here is a nice talk about git 😉 
[![Git as scifi](https://img.youtube.com/vi/akyz-RA1WQk/0.jpg)](https://www.youtube.com/watch?v=akyz-RA1WQk&list=LLdYRuKxWro5OYHNtOeBlCGQ&index=435&t=0s)

**Comment by redbluee** [comment]
I would suggest to postpone it, till the main essence of this project is barely done, supporting python knowledge and showing what nice tools there are in the python world.

**Comment by redbluee** [comment]
I can btw recommend this git book/site. It helped me a lot when i was learning to get through git.

[git book from 2009](https://git-scm.com/book/de/v1
)

I would like to attach this as compendium.

**Comment by s-weigand** [comment]
`tutorials.md` would be a good place for that I guess (see #9 )
