### ISSUE TITLE
Should we include examples in the docs?

### ISSUE THREAD

**Issue by s-weigand** [students-teach-students/python-tools-for-students#43]
Due to the nature of examples, people will learn the most if they 'play around' with them and see the changes in the result due to their changes in the code.

On the other hand, just looking them up in the dark (like blog posts/tutorials) also has the benefit of being used as a reference (i.e. you are in the subway and just want to look up how exactly that part worked).

The middle way would be to decide on a case to case basis.

**Comment by redbluee** [comment]
Im not sure, which way would be better here. My feeling tells me to leave it out, make the docs as guiding as possible, without blowing it up with stuff you can look for in the ipython notebooks.

**Comment by s-weigand** [comment]
We could also put them in a separate chapter examples, which mimics the structure of the material.Like that we won't clutter the material, but people can still have a look at the examples from the docs.

**Comment by redbluee** [comment]
> We could also put them in a separate chapter examples, which mimics the structure of the material.Like that we won't clutter the material, but people can still have a look at the examples from the docs.

Without explanations or with? I mean, the ipython notebooks are structured with explanations in markdown cells, do you just want to copy that, or simply just have the code which will be executed by the python interpreter.

**Comment by s-weigand** [comment]
I was thinking of a structure in the docs like so:
```
Chapters
    |-- <chapter_nr>_<chapter_name>
Examples
    |-- <chapter_nr>_<chapter_name>
       |-- Example1
       |-- Example2
       .
       .
       .
```
The examples themselves should have markdown cells at the top, explaining what is going on.
