### ISSUE TITLE
Create contribution guide

### ISSUE THREAD

**Issue by s-weigand** [students-teach-students/python-tools-for-students#9]
Since I'm about to make the first PR for the guide on how to use `jupyter lab`, I think we should agree on a folder/file structure, which we will use for the project. Since as of now we only have 2 members who agreed to write material at all, it would also be good to have a contribution guide, so more people might be willing to write material.

### Materials I plan on having:
* **Champters** (NB: detailed explanations of specific topics, see #3 )
* **Examples** (NB: examples that further deepen the understanding on how to solve/treat specific problems)
* **TL;DR** (MD: short summary of the chapters, similar to a cheat sheet)
* **Cheat sheet collection** (MD: links to cheat sheets )
* **Code snippeds** (NB/MD: collection of usefull codesnippeds or functions, i.e. `plot_and_fit(data, func, initial_params={})`, might be extracted from *Examples*)
* **Additional material** (MD: collection of detailed trainings, conference talks and documentations) 
* **Tutorials** (MD: collection of tutorials)

`NB=notebook`, `MD=markdown`

### My proposed folder structure:

```
Repository-root
|-- material
    |-- <chapter_nr>_<chapter_name>
        |-- data
        |-- images
        |-- <chapter_nr>_<chapter_name>.ipynb
        |-- TL_DR.md
        |-- additional_materials.md
        |-- code_snippets.md
        |-- Examples
            |-- data
                |-- <data_description>-example1.txt
                |-- ...
            |-- example1.ipynb
            |-- ...
    |-- cheat_sheets.md
    |-- tutorials.md
|-- docs
    |-- material
        |-- <chapter_nr>_<chapter_name>
           |-- <chapter_nr>_<chapter_name>.nblink
    |-- examples
        |-- <chapter_nr>_<chapter_name>
           |-- example1.nblink
```
Also as seen in #7 and #8, we could need some speeling lectors, at least for the stuff I write. 😛

**Comment by s-weigand** [comment]
The ``#`` in the path mess up links with binder, so i removed them.

**Comment by redbluee** [comment]
Folder structure and the idea behind looks very well! Let's do it that wa.

**Comment by s-weigand** [comment]
[Already started working on it](https://github.com/s-weigand/python-tools-for-students/blob/add-contribution-guide/CONTRIBUTING.md), but postponed it until the [test tooling](https://github.com/s-weigand/flake8-nb) is finished. So the contributions are automatically tested for code style.
